# Lightweight Docker Compose for Development Environment
# Uses production Supabase instead of local database

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: tokuteigino-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/tokuteigino
      - REDIS_URL=redis://host.docker.internal:6379
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${VITE_SUPABASE_PROD_URL}
      - SUPABASE_ANON_KEY=${VITE_SUPABASE_PROD_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_PROD_ANON_KEY}
    networks:
      - tokuteigino-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: tokuteigino-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_SUPABASE_URL=${VITE_SUPABASE_PROD_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_PROD_ANON_KEY}
      - VITE_SUPABASE_PROJECT_REF=${VITE_SUPABASE_PROJECT_REF:-rvbapnvvyzxlhtsurqtg}
      - VITE_APP_ENV=development
    networks:
      - tokuteigino-network
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: rebuild
          path: ./frontend/package.json

networks:
  tokuteigino-network:
    driver: bridge

volumes:
  backend_logs: